name: terraform-fmt
description: Rewrite Terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: The path containing Terraform files to format.
    required: false
    default: "."
  workspace:
    description: |
      Terraform workspace to inspect when discovering the Terraform version to use, if the version is not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
    required: false
    default: "default"
  backend_config:
    description: |
      List of Terraform backend config values, one per line. This is used for discovering the Terraform version to use, if the version is not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of Terraform backend config files to use, one per line. This is used for discovering the Terraform version to use, if the version is not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
