name: terraform-remote-state
description: Retrieves the root-level outputs from a Terraform remote state.
author: Daniel Flook

inputs:
  backend_type:
    description: The name of the Terraform plugin used for backend state
    required: true
  workspace:
    description: Terraform workspace to get the outputs for
    required: false
    default: "default"
  backend_config:
    description: List of Terraform backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of Terraform backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
