name: terraform-validate
description: Validate a Terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: The path to the Terraform module to validate
    required: false
    default: "."
  workspace:
    description: |
      Terraform workspace to use for the `terraform.workspace` value while validating. Note that for remote operations in a cloud backend, this is always `default`.

      Also used for discovering the Terraform version to use, if not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
    required: false
    default: "default"
  backend_config:
    description: |
      List of Terraform backend config values, one per line.
      This is used for discovering the Terraform version to use, if not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of Terraform backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
      This is used for discovering the Terraform version to use, if not otherwise specified. 
      See [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version#terraform-version-action) for details.
    required: false
    default: ""

outputs:
  failure-reason:
    description: |
      When the job outcome is `failure` because the validation failed, this will be set to 'validate-failed'.
      If the job fails for any other reason this will not be set.
      This can be used with the Actions expression syntax to conditionally run a step when the validate fails.

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
