name: Test pull_request_review event

on:
  - pull_request_review

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-24.04
    name: Apply approved changes on pull_request_review
    permissions:
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Plan
        uses: ./terraform-plan
        with:
          label: pull_request_review
          path: tests/workflows/pull_request_review

      - name: Apply
        uses: ./terraform-apply
        id: output
        with:
          label: pull_request_review
          path: tests/workflows/pull_request_review

      - name: Verify outputs
        env:
          OUTPUT_STRING: ${{ steps.output.outputs.output_string }}
        run: |
          if [[ "$OUTPUT_STRING" != "the_string" ]]; then
            echo "::error:: output s not set correctly"
            exit 1
          fi
