name: Respository Dispatch

on: [repository_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-24.04
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: terraform plan
        uses: ./terraform-plan
        with:
          label: repository_dispatch
          path: tests/workflows/repository_dispatch
