name: Retain images

on:
  schedule:
    - cron: 0 0 1 * *

permissions:
  contents: read

jobs:
  pull_image:
    runs-on: ubuntu-24.04
    name: Pull images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: docker pull
        run: |
          for tag in $(git tag); do
            docker pull --quiet danielflook/terraform-github-actions:$tag
          done
