name: Test terraform-fmt

on:
  - pull_request

permissions:
  contents: read

jobs:
  canonical_fmt:
    runs-on: ubuntu-24.04
    name: Canonical fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: terraform fmt
        uses: ./terraform-fmt
        with:
          path: tests/workflows/test-fmt/non-canonical

      - name: fmt-check
        uses: ./terraform-fmt-check
        with:
          path: tests/workflows/test-fmt/non-canonical
