name: Test terraform-fmt-check

on:
  - pull_request

permissions:
  contents: read

jobs:
  canonical_fmt:
    runs-on: ubuntu-24.04
    name: Canonical fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: fmt-check
        uses: ./terraform-fmt-check
        id: fmt-check
        with:
          path: tests/workflows/test-fmt-check/canonical

      - name: Check valid
        env:
          FAILURE_REASON: ${{ steps.fmt-check.outputs.failure-reason }}
        run: |
          if [[ "$FAILURE_REASON" != "" ]]; then
            echo "::error:: failure-reason not set correctly"
            exit 1
          fi

  non_canonical_fmt:
    runs-on: ubuntu-24.04
    name: Non canonical fmt
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: fmt-check
        uses: ./terraform-fmt-check
        continue-on-error: true
        id: fmt-check
        with:
          path: tests/workflows/test-fmt-check/non-canonical

      - name: Check invalid
        env:
          OUTCOME: ${{ steps.fmt-check.outcome }}
          FAILURE_REASON: ${{ steps.fmt-check.outputs.failure-reason }}
        run: |
          if [[ "$OUTCOME" != "failure" ]]; then
            echo "fmt-check did not fail correctly"
            exit 1
          fi

          if [[ "$FAILURE_REASON" != "check-failed" ]]; then
            echo "::error:: failure-reason not set correctly"
            exit 1
          fi
