name: Unit test

on:
  - push

permissions:
  contents: read

jobs:
  pytest_amd64:
    runs-on: ubuntu-24.04
    name: pytest amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          
          gpg --recv-keys C874011F0AB405110D02105534365D9472D7468F \
           && echo "C874011F0AB405110D02105534365D9472D7468F:6:" | gpg --import-ownertrust          

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_ACTIONS_GITHUB_TOKEN: No
        run: |
           GNUPGHOME=$HOME/.gnupg PYTHONPATH=image/tools:image/src pytest tests

  pytest_arm64:
    runs-on: ubuntu-24.04-arm
    name: pytest arm64
    needs: pytest_amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

          gpg --recv-keys C874011F0AB405110D02105534365D9472D7468F \
           && echo "C874011F0AB405110D02105534365D9472D7468F:6:" | gpg --import-ownertrust

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_ACTIONS_GITHUB_TOKEN: No
        run: |
           GNUPGHOME=$HOME/.gnupg PYTHONPATH=image/tools:image/src pytest tests

  docs:
    runs-on: ubuntu-24.04
    name: Check documentation
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check documentation is up-to-date
        run: |
          PYTHONPATH=docs-gen python3 docs-gen/generate.py
          git diff --exit-code

