name: Test terraform-apply using HTTP Credentials

on:
  - pull_request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  git_http_full_path_credentials:
    runs-on: ubuntu-24.04
    name: git+http full path creds
    env:
      TERRAFORM_HTTP_CREDENTIALS: |
        github.com/dflook/hello=dflook:notapassword
        github.com/hello=dflook:stillnotapassword
        github.com/dflook/terraform-github-actions-dev.git=dflook:${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply
        uses: ./terraform-apply
        id: output
        with:
          path: tests/workflows/test-http
          auto_approve: true

      - name: Verify outputs
        env:
          OUTPUT_GIT_HTTPS: ${{ steps.output.outputs.git_https }}
        run: |
          if [[ "$OUTPUT_GIT_HTTPS" != "hello" ]]; then
            echo "::error:: output not set correctly"
            exit 1
          fi

  git_http_partial_path_credentials:
    runs-on: ubuntu-24.04
    name: git+http partial path creds
    env:
      TERRAFORM_HTTP_CREDENTIALS: |
        github.com/dflook/hello=dflook:notapassword
        github.com/hello=dflook:stillnotapassword
        github.com/dflook=dflook:${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply
        uses: ./terraform-apply
        id: output
        with:
          path: tests/workflows/test-http
          auto_approve: true

      - name: Verify outputs
        env:
          OUTPUT_GIT_HTTPS: ${{ steps.output.outputs.git_https }}
        run: |
          if [[ "$OUTPUT_GIT_HTTPS" != "hello" ]]; then
            echo "::error:: output not set correctly"
            exit 1
          fi

  git_http_no_path_credentials:
    runs-on: ubuntu-24.04
    name: git+http no path
    env:
      TERRAFORM_HTTP_CREDENTIALS: |
        github.com/dflook/hello=dflook:notapassword
        github.com/hello=dflook:stillnotapassword
        github.com=dflook:${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply
        uses: ./terraform-apply
        id: output
        with:
          path: tests/workflows/test-http
          auto_approve: true

      - name: Verify outputs
        env:
          OUTPUT_GIT_HTTPS: ${{ steps.output.outputs.git_https }}
        run: |
          if [[ "$OUTPUT_GIT_HTTPS" != "hello" ]]; then
            echo "::error:: output not set correctly"
            exit 1
          fi

  git_no_credentials:
    runs-on: ubuntu-24.04
    name: git+http no creds
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply
        uses: ./terraform-apply
        continue-on-error: true
        id: apply
        with:
          path: tests/workflows/test-http
          auto_approve: true

      - name: Check failed
        env:
          OUTCOME: ${{ steps.apply.outcome }}
        run: |
          if [[ "$OUTCOME" != "failure" ]]; then
            echo "did not fail correctly with no http credentials"
            exit 1
          fi

  http_credentials:
    runs-on: ubuntu-24.04
    name: http module source
    env:
      TERRAFORM_HTTP_CREDENTIALS: |
        5qcb7mjppk.execute-api.eu-west-2.amazonaws.com=dflook:hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create dummy credential file
        env:
          RUNNER_TEMP_D: ${{ runner.temp }}
        run: |
          mkdir -p "$RUNNER_TEMP_D/_github_home"
          cp tests/workflows/test-http/http-module/netrc "$RUNNER_TEMP_D/_github_home/.netrc"
          ls -la "$RUNNER_TEMP_D"

      - name: Apply
        uses: ./terraform-apply
        id: output
        with:
          path: tests/workflows/test-http/http-module
          auto_approve: true

      - name: Verify outputs
        env:
          OUTPUT_HTTPS: ${{ steps.output.outputs.https }}
          RUNNER_TEMP_D: ${{ runner.temp }}
        run: |
          if [[ "$OUTPUT_HTTPS" != "hello" ]]; then
            echo "::error:: output not set correctly"
            exit 1
          fi
          
          # Check the credential file is as before
          diff tests/workflows/test-http/http-module/netrc "$RUNNER_TEMP_D/_github_home/.netrc"

  http_no_credentials:
    runs-on: ubuntu-24.04
    name: http module source with no credentials
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply
        uses: ./terraform-apply
        continue-on-error: true
        id: apply
        with:
          path: tests/workflows/test-http/http-module
          auto_approve: true

      - name: Check failed
        env:
          OUTCOME: ${{ steps.apply.outcome }}
        run: |
          if [[ "$OUTCOME" != "failure" ]]; then
            echo "did not fail correctly with no http credentials"
            exit 1
          fi
